FROM python:3.12-alpine

RUN apk upgrade --no-cache libuuid

RUN addgroup -S appgroup \
    && adduser -S -G appgroup appuser

WORKDIR /app

COPY --chown=appuser:appgroup app.py .

USER appuser

EXPOSE 8080

CMD ["python", "app.py"]